### ISSUE TITLE
Improve HF model metadata

### ISSUE THREAD

**Issue by NielsRogge** [Vision-CAIR/LongVU#5]
Hi @xiaoqian-shen congrats on this work!

Really nice to see you publishing the models on the 🤗 hub along with a very nice Gradio demo.

Would it be possible to link the models + demo to the [paper page](https://huggingface.co/papers/2410.17434)? The paper page is a new feature on the hub which lets people discuss a paper and find artifacts (your models, demo for instance).

A model/demo can be linked to it by including the arxiv or https://huggingface.co/papers/2410.17434 link in the respective READMEs. Here's an example: https://huggingface.co/Vision-CAIR/LongVU_Qwen2_7B/discussions/1.

Besides that, would be great to add the video-text-to-text tag to each of the model repos, which makes sure the models can be found at https://huggingface.co/models?pipeline_tag=video-text-to-text&sort=trending. Here's an example PR: https://huggingface.co/Vision-CAIR/LongVU_Qwen2_7B/discussions/2.

Finally, safetensors could be adopted: https://huggingface.co/Vision-CAIR/LongVU_Qwen2_7B/discussions/4.

Thanks!

Niels from HF

**Comment by xiaoqian-shen** [comment]
Thanks @NielsRogge for this detailed HF metadata instruction!
Now the models are linked with the paper and tagged with video-text-to-text. 
And the model weight `pytorch_model.bin` is replaced with safetensors format.

Best,
Xiaoqian

**Comment by jadechoghari** [comment]
@xiaoqian-shen superb work 🔥 — instead of requiring users to manually clone the model and place it in the folder, the uploaded checkpoint on the hub could be a bit modified so it’s automatically downloaded/ transformers compatible and ready to use.

Ex (working for this ckpt):

```python
from builder import load_pretrained_model

tokenizer, model, image_processor, context_len = load_pretrained_model(
    "jadechoghari/LongVU_Qwen2_7B", None, "cambrian_qwen",
)

```
https://huggingface.co/jadechoghari/LongVU_Qwen2_7B
you just need to add the repo id and it'll work!

cc @NielsRogge or me if you have any other questions.

I’ll open a PR soon once all the ckpts are complete! 😄

**Comment by NielsRogge** [comment]
Great, thanks a lot @xiaoqian-shen !
